### ISSUE TITLE
InvalidParameterException: Unsupported resource type: cluster

### ISSUE THREAD

**Issue by moisesrodriguez** [karanpratapsingh/preview-environments#7]
I'm getting this error when the provision step. I do not see anywhere in the code anything with type cluster that would give me an idea where the error comes from.

![Screen Shot 2022-02-07 at 17 19 26](https://user-images.githubusercontent.com/3869040/152888643-1346d5f4-dbdb-4e7c-a2e7-d7aa297bca89.png)

**Comment by moisesrodriguez** [comment]
I believe the previous error was because I had to manually create the ECS Cluster myself and then pass the name to config.ts. But now I'm getting `Error: : InvalidParameterException: Tasks cannot be empty`:

![Screen Shot 2022-02-07 at 18 19 25](https://user-images.githubusercontent.com/3869040/152894165-f142ae2f-2043-4a25-8a0a-01ed2d0534e7.png)

**Comment by karanpratapsingh** [comment]
yes, the cluster is required, this script only creates/removes the task. I think this issue is coming from somewhere here https://github.com/karanpratapsingh/preview-environments/blob/master/infrastructure/iam.tf. 

Steps to debug:

- add a console log there for this variable `const params: AWS.ECS.RunTaskRequest `
- now you can check all the params, and use it to run the task def manually from your terminal to debug

**Comment by moisesrodriguez** [comment]
This last error was fixed with the PR https://github.com/karanpratapsingh/preview-environments/pull/10
